package rh_java;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 * @author Juliana
 */
public class CadRequisito extends javax.swing.JInternalFrame {

    private List<Requisito> requisitos;
    
    public CadRequisito() {

        RequisitoDAO rd = new RequisitoDAO();
   
        requisitos = rd.listar();
        initComponents();
        
        BindingGroup bg = new BindingGroup();
        
        JTableBinding tb = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ_WRITE,
            requisitos,
            tblRequisito
        ); 
        
        JTableBinding.ColumnBinding cb = tb.addColumnBinding(BeanProperty.create("descricao"));
        cb.setColumnName("Descrição");
        
        bg.addBinding(tb);
        
        Binding b = Bindings.createAutoBinding(
            AutoBinding.UpdateStrategy.READ_WRITE, 
            tblRequisito,
            BeanProperty.create("selectedElement.descricao"),
            txtRequisito,
            BeanProperty.create("text")
        );
        
        bg.addBinding(b);
        bg.bind();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        lblRequisito = new javax.swing.JLabel();
        txtRequisito = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequisito = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Contratar Funcionário");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        lblRequisito.setText("Descrição do Requisito");

        tblRequisito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequisito);
        if (tblRequisito.getColumnModel().getColumnCount() > 0) {
            tblRequisito.getColumnModel().getColumn(0).setResizable(false);
            tblRequisito.getColumnModel().getColumn(1).setResizable(false);
            tblRequisito.getColumnModel().getColumn(2).setResizable(false);
            tblRequisito.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRequisito, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRequisito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblRequisito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRequisito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnIncluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        if( getDesktopPane() instanceof AreadeTrabalho )
        {
            ( (AreadeTrabalho)getDesktopPane() ).fecharCadRequisito();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        RequisitoDAO rd = new RequisitoDAO();
    
        if(tblRequisito.getSelectedRows().length > 0){
            int selecionados = tblRequisito.getSelectedRows().length;
            for(int i = 0; i < selecionados; i++){
                if(rd.apagar(requisitos.get(tblRequisito.getSelectedRows()[0]))){
                    JOptionPane.showMessageDialog(null, "Registro apagado com sucesso");
                } else {
                    JOptionPane.showMessageDialog(null, "Não foi possível excluir o registro");
                }
                requisitos.remove(tblRequisito.getSelectedRows()[0]);
            }
            txtRequisito.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para excluir");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        if(tblRequisito.getSelectedRows().length > 0){
            RequisitoDAO rd = new RequisitoDAO();
                
            if(rd.alterar(requisitos.get(tblRequisito.getSelectedRow()))){
                JOptionPane.showMessageDialog(null, "Registro alterado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível alterar o registro");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para alterar");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed

        if(txtRequisito.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite um valor antes de adicionar");
        } else {
            Requisito r = new Requisito(txtRequisito.getText());
            requisitos.add(r);
            txtRequisito.setText("");
            RequisitoDAO rd = new RequisitoDAO();
            if(rd.inserir(r)){
                JOptionPane.showMessageDialog(null, "Registro inserido com sucesso");
            }
            else{
                JOptionPane.showMessageDialog(null, "Não foi possível inserir o registro");
            }
        }
    }//GEN-LAST:event_btnIncluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRequisito;
    private javax.swing.JTable tblRequisito;
    private javax.swing.JTextField txtRequisito;
    // End of variables declaration//GEN-END:variables
}
