/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rh_java;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author marco
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /*@Override
    public void paint(Graphics g){
        super.paint(g);
    
        g.setColor(Color.red);
        g.fillRect(10, 10 , 720, 300);
        
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AberturaVagaButton = new javax.swing.JButton();
        AberturadeVagaButton = new javax.swing.JButton();
        ProcessamentoButton = new javax.swing.JButton();
        ContatoButton = new javax.swing.JButton();
        StatusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - Sistema RH");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(824, 384));
        setPreferredSize(new java.awt.Dimension(824, 384));
        setResizable(false);
        setSize(new java.awt.Dimension(824, 384));

        AberturaVagaButton.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        AberturaVagaButton.setText("Requisitos");
        AberturaVagaButton.setToolTipText("Analisar e Criar Requisitos");
        AberturaVagaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AberturaVagaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AberturaVagaButton.setOpaque(false);
        AberturaVagaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AberturaVagaButtonActionPerformed(evt);
            }
        });

        AberturadeVagaButton.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        AberturadeVagaButton.setMnemonic('A');
        AberturadeVagaButton.setText("Criar Vaga");
        AberturadeVagaButton.setToolTipText("Solicitar Abertura de Vaga");
        AberturadeVagaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AberturadeVagaButton.setFocusPainted(false);
        AberturadeVagaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AberturadeVagaButton.setIconTextGap(0);
        AberturadeVagaButton.setOpaque(false);
        AberturadeVagaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AberturadeVagaButtonActionPerformed(evt);
            }
        });

        ProcessamentoButton.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        ProcessamentoButton.setText("Processamento");
        ProcessamentoButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ProcessamentoButton.setMaximumSize(new java.awt.Dimension(100, 100));
        ProcessamentoButton.setMinimumSize(new java.awt.Dimension(100, 100));
        ProcessamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessamentoButtonActionPerformed(evt);
            }
        });

        ContatoButton.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        ContatoButton.setText("Contato");
        ContatoButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoButtonActionPerformed(evt);
            }
        });

        StatusButton.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        StatusButton.setText("Status");
        StatusButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(AberturadeVagaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(AberturaVagaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(StatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ProcessamentoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ContatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AberturadeVagaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AberturaVagaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProcessamentoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContatoButtonActionPerformed

    private void StatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusButtonActionPerformed

    private void ProcessamentoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessamentoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProcessamentoButtonActionPerformed

    private void AberturaVagaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AberturaVagaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AberturaVagaButtonActionPerformed

    private void AberturadeVagaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AberturadeVagaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AberturadeVagaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AberturaVagaButton;
    private javax.swing.JButton AberturadeVagaButton;
    private javax.swing.JButton ContatoButton;
    private javax.swing.JButton ProcessamentoButton;
    private javax.swing.JButton StatusButton;
    // End of variables declaration//GEN-END:variables
}
