/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rh_java;

/**
 *
 * @author marco
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreadeTrabalho = new rh_java.AreadeTrabalho();
        mnbBarraMenu = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        mnitContratarFunc = new javax.swing.JMenuItem();
        mnitCadastrarUsuario = new javax.swing.JMenuItem();
        mnitCadInstParceira = new javax.swing.JMenuItem();
        mnVagas = new javax.swing.JMenu();
        mnitCadastrarVaga = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnCadastro.setText("Cadastro");

        mnitContratarFunc.setText("Contratar Funcionário");
        mnitContratarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitContratarFuncActionPerformed(evt);
            }
        });
        mnCadastro.add(mnitContratarFunc);

        mnitCadastrarUsuario.setText("Cadastrar Usuário");
        mnitCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitCadastrarUsuarioActionPerformed(evt);
            }
        });
        mnCadastro.add(mnitCadastrarUsuario);

        mnitCadInstParceira.setText("Cadastrar Instituição");
        mnitCadInstParceira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitCadInstParceiraActionPerformed(evt);
            }
        });
        mnCadastro.add(mnitCadInstParceira);

        mnbBarraMenu.add(mnCadastro);

        mnVagas.setText("Vagas");

        mnitCadastrarVaga.setText("Cadastrar Vaga");
        mnitCadastrarVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitCadastrarVagaActionPerformed(evt);
            }
        });
        mnVagas.add(mnitCadastrarVaga);

        mnbBarraMenu.add(mnVagas);

        setJMenuBar(mnbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreadeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreadeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitContratarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitContratarFuncActionPerformed
        // TODO add your handling code here:
        AreadeTrabalho.AbrirContFuncionario();
    }//GEN-LAST:event_mnitContratarFuncActionPerformed

    private void mnitCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        AreadeTrabalho.AbrirCadastroUsuario();
    }//GEN-LAST:event_mnitCadastrarUsuarioActionPerformed

    private void mnitCadastrarVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitCadastrarVagaActionPerformed
        // TODO add your handling code here:
        AreadeTrabalho.abrirCriarVaga();
    }//GEN-LAST:event_mnitCadastrarVagaActionPerformed

    private void mnitCadInstParceiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitCadInstParceiraActionPerformed
        // TODO add your handling code here:
        AreadeTrabalho.abrirInstituicaoParceira();
    }//GEN-LAST:event_mnitCadInstParceiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rh_java.AreadeTrabalho AreadeTrabalho;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnVagas;
    private javax.swing.JMenuBar mnbBarraMenu;
    private javax.swing.JMenuItem mnitCadInstParceira;
    private javax.swing.JMenuItem mnitCadastrarUsuario;
    private javax.swing.JMenuItem mnitCadastrarVaga;
    private javax.swing.JMenuItem mnitContratarFunc;
    // End of variables declaration//GEN-END:variables
}
